name = "MccDaqHats"
uuid = "5205887b-b2f8-40cf-afdf-6e54d6d6c035"
authors = ["jakezw <jake.zwart@sympatico.ca> and contributors"]
version = "0.1.4"

[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
WiringPi = "56b06491-0088-44d9-858f-9bc194f2c904"

[compat]
CEnum = "0.5"
WiringPi = "0.2.2"
julia = "1.10.9"
