name = "MccDaqHats"
uuid = "5205887b-b2f8-40cf-afdf-6e54d6d6c035"
authors = ["jakezw <jake.zwart@sympatico.ca> and contributors"]
version = "0.1.4"

[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
Gpiod = "fc5cb0c8-de5a-498d-9e5a-0d5c8fd467e9"

[compat]
julia = "1.10.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
